### ISSUE TITLE
Wrong chrome-sandbox permissions in the RPM package 

### ISSUE THREAD

**Issue by aleksey-novikov** [jgraph/drawio-desktop#150]
File /opt/draw.io/chrome-sandbox must has SUID-bit enabled, but RPM package miss it.
Without this application terminates with error :

[12597:0819/144912.726910:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/draw.io/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)

**Comment by letompouce** [comment]
It did happen on Debian on [a fresh 11.1.4 install](https://github.com/jgraph/drawio-desktop/issues/140#issuecomment-524876408) so I `chmod`'ed it.

Today, upgrading to 11.2.4 got the file modes set back so I had to `chmod`  it again.

**Comment by davidjgraph** [comment]
How about 11.2.5?

**Comment by aleksey-novikov** [comment]
> How about 11.2.5?

Error still exists

**Comment by mayanksuman** [comment]
Error still exist with 11.3.0 version deb.

**Comment by shoffmeister** [comment]
FWIW, I just successfully installed
`sudo dnf install ./draw.io-x86_64-12.1.0.rpm` on Fedora 30, and all seems well out of the box.

On the file system I see
```
-rwxr-xr-x.  1 root root   5099032 Oct 10 18:58 chrome-sandbox
-rwxr-xr-x.  1 root root 112452376 Oct 10 18:58 drawio
```

**Comment by davidjgraph** [comment]
This should be fixed in 12.1.0, we adjusted the linux build process.

**Comment by aleksey-novikov** [comment]
Not resolved. Error still reproduce on CentOS 7.6

$ /opt/draw.io/drawio 
[9012:1017/131848.319278:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/draw.io/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)

$ rpmquery draw.io
draw.io-12.1.0-253.x86_64

**Comment by davidjgraph** [comment]
We built using the 22.1.0 pre-release, it should be fixed. I will close, if not fixed say so and I'll re-open.

**Comment by camlafit** [comment]
Hello 
I got same behavior with last deb packaging  ( 14.4.3 ), solved with a chown and chmod change on /opt/draw.io/chrome-sandbox

Thanks a lot

**Comment by alexander-haller** [comment]
I think the current appimage still has the same problem:

 ./drawio-x86_64-14.5.1.AppImage 
[4881:0414/144141.806886:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_drawio4n3Vvi/chrome-sandbox is owned by root and has mode 4755.

Debian 10.9 mit Kernel 4.19.0-16-amd64

**Comment by alexander-haller** [comment]
With the new Debian 11 it works for me now.
Linux 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux

**Comment by camlafit** [comment]
Hello

I confirm also  :) Last deb looks ok on my Debian bulleyes \o/

**Comment by cybre-finn** [comment]
In Kubuntu 24.10, this occurred with my installation using drawio-amd64-25.0.2.deb

Was fixed by chmodding, but just wanted to let you know.

**Comment by pohlondrej** [comment]
Got this issue today, Kubuntu 24.10. draw.io version 26.0.9. Fixed by chmod.

**Comment by davidjgraph** [comment]
Can someone submit a PR please
