### ISSUE TITLE
Change autosave scheduling or make it toggleable?

### ISSUE THREAD

**Issue by zack6849** [jgraph/drawio-desktop#199]
Hi There!

I'm using this and when i make a large chart, every single time i add a field, it hangs the UI and freezes up for a good second or two

It'd be ideal if i could tell it to auto save like every 5 minutes, or disable autosave altogether if i so choose. 

Somewhat related: #173 

Thanks!

**Comment by davidjgraph** [comment]
How big is the file on the file system?

**Comment by zack6849** [comment]
Disregard, I just noticed the autosave **is** toggle able, the file is 40KB on disk, and i have an SSD.

**Comment by zack6849** [comment]
It may be helpful to have a threshold or something where if saving takes more than a set amount of time it'd tell people if saving is slow they can disable autosave or something of the like

**Comment by davidjgraph** [comment]
I think #173 is the correct fix, we need to make the saving async.

**Comment by zack6849** [comment]
Another thing i ran into you might want to account for is I closed while saving and lost this entire file yesterday, presumably i hit ctrl + s and it wiped the file before it finished saving, not sure if it'd be viable to save it to a new file and THEN overwrite the old file in place or something.

**Comment by davidjgraph** [comment]
Is that running the latest version?

**Comment by zack6849** [comment]
DrawIO desktop v 12.5.0 from arch user repos

**Comment by davidjgraph** [comment]
We've never released anything after 12.4.2 to date, I hope the author is testing those releases properly...

**Comment by zack6849** [comment]
Huh, that's... odd.
https://aur.archlinux.org/packages/drawio-desktop/

So i'm essentially running the master branch presumably, even with unreleased changes?

**Comment by davidjgraph** [comment]
They will be updating the drawio subproject and building everything as a release of the desktop with the version of the sub-project. The reason we're on a slower release schedule to drawio is there needs to be some manual testing on each OS for the basic file operations on each release. If that's being automatically put together, it should generally be good, but we go for stability over speed exactly because of file issues.

**Comment by davidjgraph** [comment]
https://aur.archlinux.org/packages/drawio-desktop-bin/ is the one your should be using.

I looked through https://aur.archlinux.org/packages/drawio-desktop/ , this is not a stable build, it needs to be removed with urgency.

**Comment by zack6849** [comment]
Thanks david, I'll switch to the binary package now, hopefull I won't run into any more hiccups.

Thanks for your prompt response and help!

**Comment by dvalter** [comment]
@davidjgraph I've been drawio-desktop maintainter at AUR for last few weeks.
Historically this package (among others in AUR/Arch) was using shared election provided by Arch.

Because of it being not familiar with draw.io release scheme I packaged umstable releases.
I feel sorry for making providing unstable builds and making users complain about unstabilities in unstable code to you.

**Comment by dvalter** [comment]
@davidjgraph since we use electron from Arch repository (currently 7.18) to launch draw.io as a local app, it's unlikely to be an issue.
However thank you for pointing it out, other dependencies may actually be outdated. I've updated package to use package.json and yarn.lock from drawio-desktop tarball.

**Comment by davidjgraph** [comment]
@dvalter You got a lucky break, actually, avoiding https://github.com/electron-userland/electron-builder/issues/4505 with Electron 6.

That said, we still don't test the HEAD of drawio master in electron until we come to desktop release. 20% of the time it's broken when we start testing the release candidate, this will hit you.

**Comment by dvalter** [comment]
@davidjgraph the way [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=drawio-desktop) is currently written, it require both tarballs of drawio and drawio-desktop of the same version, so it should eliminate possibility of building it from unstable sources

**Comment by davidjgraph** [comment]
OK, that's just been changed? I ask since I wonder how a 12.5.0 release was built, https://aur.archlinux.org/cgit/aur.git/log/?h=drawio-desktop, for example.

**Comment by dvalter** [comment]
@davidjgraph it was, as I wrote, because I was misunderstanding the difference between drawio and drawio-desktop releases.
