### ISSUE TITLE
Cmd + c/v not working with alternate modifier keys in Mac OS

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio-desktop#2]
On mac cmd + c and cmd + v keyboard shortcuts aren't working for copy/paste. The menu does work.

**Comment by michaelmcdonald** [comment]
Some more details as I'm experiencing the same issue:
*OPERATING SYSTEM:* macOS Sierra (v10.12.6)
*DRAWIO VERSION:* v7.1.9
*ISSUE:* Any text field where text can be entered does not accept the keyboard hotkeys for copy / paste (CMD + C / CMD + V) on the desktop application. The web application works without issue.

**Comment by DaOriSin** [comment]
no resolution？

**Comment by michaelmcdonald** [comment]
Updated to v7.3.5 and the issue still persists.

**Comment by davidjgraph** [comment]
If it were fixed, the issue would have been closed. If the issue isn't closed, you can assume it's not fixed.

**Comment by alderg** [comment]
Like @michaelmcdonald pointed out this is a bug in Electron (ie. copy/paste isn't working for any text element), so we need to wait for them to fix this.

**Comment by davidjgraph** [comment]
https://github.com/electron/electron/issues/2308

**Comment by davidjgraph** [comment]
Fixed in 7.7.2

**Comment by corymayer** [comment]
The shortcuts are still not working for me on the desktop version. I have the same keyboard setup as the person in this issue: https://github.com/jgraph/drawio-desktop/issues/38

**Comment by alexhayes** [comment]
The shortcuts do not work for me on the web version either 😢

**Comment by davidjgraph** [comment]
Issue for online version is ubuntu only, https://github.com/jgraph/drawio/issues/262. If you can repeat on other OS, please provide environment on other project.

**Comment by cpierson-gnw** [comment]
> Issue for online version is ubuntu only, [jgraph/drawio#262](https://github.com/jgraph/drawio/issues/262). If you can repeat on other OS, please provide environment on other project.

OS: macOS Mojave 10.14.6 (18G87)
Desktop version: 12.1.0

Not only do shortcuts not work for me on desktop, I cannot copy and paste even using menu options. I get the same error when trying to duplicate a page.
<img width="554" alt="Screen Shot 2019-10-23 at 12 31 39 PM" src="https://user-images.githubusercontent.com/55599881/67414466-24531b00-f591-11e9-99ac-d18be5a73b5a.png">

**Comment by alderg** [comment]
Does this happen only with a specific selection of cells or with any cell, like a single rectangle?

**Comment by cpierson-gnw** [comment]
No specific selection, happens with any. However, I was able to get it working on the web client but not desktop. I am using a plug-in that was not reloaded when I moved to a new machine. Loading the plug-in to the web client works, but does not fix the issue on desktop, even after closing, restarting, and confirming the plug-in on restart.

**Comment by alderg** [comment]
So the plugin produces invalid XML that is causing this error to appear?

**Comment by cpierson-gnw** [comment]
No, the plug-in doesn't load on desktop. See attached images, one from web browser, other from desktop. C4 Model is missing - the plug-in is here: https://tobiashochguertel.github.io/c4-draw.io/c4.js
<img width="221" alt="Screen Shot 2019-10-30 at 10 24 22 AM" src="https://user-images.githubusercontent.com/55599881/67866639-a4343480-faff-11e9-80ad-c8190d67792e.png">
<img width="215" alt="Screen Shot 2019-10-30 at 10 25 09 AM" src="https://user-images.githubusercontent.com/55599881/67866641-a4cccb00-faff-11e9-9116-edb83e86345d.png">

**Comment by alderg** [comment]
But the file, ie the XML, was created using that plugin, then loaded into the desktop version? AFAIK the C4 plugin produces invalid XML, we have reached out to the author and asked for a fix some time ago.

**Comment by alderg** [comment]
The desktop version does not load the plugin, it is sandboxed, and the plugin overrides the I/O system of the editor and defines special constructors, which are not available in the desktop if the plugin does not load.

**Comment by constantinov** [comment]
> On mac cmd + c and cmd + v keyboard shortcuts aren't working for copy/paste. The menu does work.

have same issue when connecting an external usb keyboard to my mac. cmd + c and cmd + v keyboard shortcuts work on the original keyboard, but do not work on the external usb keyboard. cmd + c and cmd + v works fine in other apps.

**Comment by likaihz** [comment]
> > On mac cmd + c and cmd + v keyboard shortcuts aren't working for copy/paste. The menu does work.
> 
> have same issue when connecting an external usb keyboard to my mac. cmd + c and cmd + v keyboard shortcuts work on the original keyboard, but do not work on the external usb keyboard. cmd + c and cmd + v works fine in other apps.
> The issue only exists when key modifiers enabled:
> <img alt="image" width="286" src="https://user-images.githubusercontent.com/31038630/68393483-d46d7a00-0174-11ea-9786-3d57592c0c60.png">

same issue... any ideas?

**Comment by davidjgraph** [comment]
Please do not "me too", "any ideas", "eta", etc. It spams others and adds nothing to the conversation.

**Comment by LeungGeorge** [comment]
> > On mac cmd + c and cmd + v keyboard shortcuts aren't working for copy/paste. The menu does work.
> 
> have same issue when connecting an external usb keyboard to my mac. cmd + c and cmd + v keyboard shortcuts work on the original keyboard, but do not work on the external usb keyboard. cmd + c and cmd + v works fine in other apps.
> The issue only exists when key modifiers enabled:
> <img alt="image" width="286" src="https://user-images.githubusercontent.com/31038630/68393483-d46d7a00-0174-11ea-9786-3d57592c0c60.png">

same problem。
but when press shortcuts at the right side cmd(alias of option), it works

**Comment by Cloudzay** [comment]
> > > On mac cmd + c and cmd + v keyboard shortcuts aren't working for copy/paste. The menu does work.
> > 
> > 
> > have same issue when connecting an external usb keyboard to my mac. cmd + c and cmd + v keyboard shortcuts work on the original keyboard, but do not work on the external usb keyboard. cmd + c and cmd + v works fine in other apps.
> > The issue only exists when key modifiers enabled:
> > <img alt="image" width="286" src="https://user-images.githubusercontent.com/31038630/68393483-d46d7a00-0174-11ea-9786-3d57592c0c60.png">
> 
> same problem。
> but when press shortcuts at the right side cmd(alias of option), it works

exactly the same, version 12.6.5

**Comment by edianannink** [comment]
Same issue. Very annoying because I need the remapping. Not using an Apple keyboard :/

**Comment by davidjgraph** [comment]
Please vote up the original issue, no +1, me too...

**Comment by ashrafteleb** [comment]
I cannot reproduce the issue on 10.15.6 with an external KB using the same key modifier.

Can anyone confirm it is still an issue?

**Comment by imageslr** [comment]
Still an issue in 10.15.5, please see https://github.com/jgraph/drawio-desktop/issues/326#issuecomment-693976299

**Comment by EgleKat** [comment]
Still an issue in 13.7.9

**Comment by e-desouza** [comment]
Still an issue with 14.1.8

**Comment by ashrafteleb** [comment]
The MacOS external keyboard copy/paste issue will be fixed in the next release
