### ISSUE TITLE
Opening drawio opens last editted document and claims unsaved changes

### ISSUE THREAD

**Issue by TooManyStacks** [jgraph/drawio-desktop#2137]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When I restart my system, open up drawio it opens the last saved / worked on diagram, and shows the popup with unsaved changes. When I press it, it prompts for a file name, as if it is a new diagram. When I then overwrite the diagram, close and reopen, it sometimes prompts me again.

I save my diagrams on a onedrive folder.

**To Reproduce**
1. Edit diagram and save to onedrive.
2. Open drawio (preferably after a reboot)
3. It opens the last diagram by itself, showing unsaved changes (not a 100 % chance)

**Expected behavior**
The normal screen where I can create a new diagram or open an existing one.

**Screenshots**
I do not have any at the moment, but will add when it happens again (or is required).

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 27.0.9

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
Seems like the issues https://github.com/jgraph/drawio-desktop/issues/1473 and https://github.com/jgraph/drawio-desktop/issues/1127

**Comment by davidjgraph** [comment]
Please try using a folder other than OneDrive sync. There's a lot of strange behaviours using OneDrive sync'ed folders.

**Comment by TooManyStacks** [comment]
If this is an issue with drawio and OneDrive, I guess I will have to learn to live with it ;) Ty.

**Comment by alderg** [comment]
Should be fixed.

**Comment by Nivarrym** [comment]
Still happens to me in v28.2.5 of Desktop App, using regular folder, not a cloud synced one. Just lost a big chunk of progress on my diagram due to being mislead by this behavior

**Comment by alderg** [comment]
Try the latest https://get.draw.io
