### ISSUE TITLE
PDF resolution shrinkage

### ISSUE THREAD

**Issue by ZichaoHuang** [jgraph/drawio-desktop#30]
After issue #28 was fixed, the exported PDF was always shrunk.
For instance, I exported a diagram of 403\*484 (after cropped), but the resolution of the exported PDF was 302\*363.
I exported my diagram through both "Export as - PDF - Crop" and "Export as - Advanced - Format:PDF, Zoom:100%, Width:403, Height:484", the exported PDF was always shrunk to around 75% of the original cropped diagram (302/403 = 0.749).
I have tried to export many of my diagram and all the exported PDFs were shrunk to around 75% of the original cropped diagram.
BTW, the resolution of the PDF I exported from the exact same diagram two weeks ago (before issue #28) is 403\*485.

**Comment by alderg** [comment]
Fixed in 8.5.11.n Thanks for the report!

**Comment by ZichaoHuang** [comment]
@alderg I have tested in draw.io 8.5.11 on macOS 10.13.4 yet the shrinkage problem is still there.

**Comment by alderg** [comment]
We have deployed another fix.

**Comment by ZichaoHuang** [comment]
@alderg I have tested in draw.io 8.5.14 on macOS 10.13.4 via "Export as - PDF - Crop" and "Export as - Advanced - PDF", and the shrinkage problem was still there.
The only difference is that the exported PDF was shrunk to 72% (290/403 = 0.719) rather than 75% as I mentioned before.

**Comment by davidjgraph** [comment]
What browser are you using? Does this happen for any diagram, i.e. I would see it for any diagram I create?

**Comment by ZichaoHuang** [comment]
@davidjgraph I am using Chrome 66.0.3359.139 and this problem does happen to any of my diagram.

**Comment by ZichaoHuang** [comment]
@davidjgraph For testing this problem, I create a new diagram with only a circle with 80pt width and 80pt height and try to export it with "Export as - Advanced - PDF".
The export setting is as follows.
![jietu20180430-214410 2x](https://user-images.githubusercontent.com/11463395/39430170-ae0a6f1e-4cbf-11e8-9c8e-915f1b39450c.jpg)
However, the resolution of the exported PDF is 58*59, which is around 72% (58/81 = 0.716) of the original cropped diagram.

**Comment by ashrafteleb** [comment]
I have checked the pdf size of the given sample file using Gimp and it
shows 81x82

It depends on the dpi (we use 100 pixel/inch). May I know which program do
you use to open the pdf?




I have used an online web site to convert the pdf to a jpg image and the
result was 121x123 since it uses 150 dpi

**Comment by ZichaoHuang** [comment]
I open the pdf file with [PDF Expert](https://pdfexpert.com/) or Preview on macOS and Adobe Acrobat Reader DC on Windows 10.

**Comment by ZichaoHuang** [comment]
@ashrafteleb In the Advanced export menu, what is the unit of measurement of the **Width** and the **Height**?

**Comment by ashrafteleb** [comment]
The unit of measurement is pixels and we use dpi of 100

On Adobe, the point unit is based on 72 dpi (hence the 72% scaling down)
https://forums.adobe.com/thread/2140211

We have to use 100 pixel per inch to generate correct page size. Try
exporting a letter page size and check the size in Adobe and it will be
correct in inches.


Letter page size (8.5" x 11")


Thanks
