### ISSUE TITLE
copy and paste are not woring in macOS Desktop Version 13.3.5

### ISSUE THREAD

**Issue by NasserGo** [jgraph/drawio-desktop#326]
command +c  and command + v

**Comment by ashrafteleb** [comment]
More details please, we cannot reproduce. Did you reassign keys?

**Comment by williamfligor** [comment]
I'm also having this issue on macOS. When I press cmd+c I see the "Edit" section of the toolbar flash blue, but it has no effect. Same with paste.

Copy pasting does work through the right click menu but not with keyboard shortcuts.

**Comment by ashrafteleb** [comment]
@williamfligor Anything special in your system settings (e.g, keys assignment)?

**Comment by z1234504** [comment]
Copying and pasting doesn't work when I'm using an external keyboard, but using the Mac's keyboard is fine

**Comment by NasserGo** [comment]
external keyboard not work ,  magic keyboard is fine

**Comment by NasserGo** [comment]
but command+z is working

**Comment by williamfligor** [comment]
Looks like my issue is related to #38 -- but command+z, command+d, etc work fine. Only copy/cut/paste stop working.

**Comment by NasserGo** [comment]
fixed in 13.4.5

**Comment by michalkz** [comment]
the issue is still present in 13.5.7, i assign ctrl to cmd and cmd to ctrl on external keyboard
ctrl+c is not working until I press 'cmd' once

**Comment by imageslr** [comment]
This issue is still present in 13.6.2. 

Here is more information:
- Copy pasting does work through the right click menu.
- Copying and pasting doesn't work when I'm using an external keyboard, but using the Mac's keyboard is fine
- When I press cmd+c I see the "Edit" section of the toolbar flash blue, but it has no effect. Same with paste.
- I'm using Filco Bluetooth Keyboard now. And I switch **Option** and **Command** key in system setting. 
- If I switch the two keys as default, copy pasting works fine!!!

![image](https://user-images.githubusercontent.com/17822028/93429147-45cc9c00-f8f3-11ea-8498-239208f4c45c.png)


So I guess that might be the reason of copy pasting not working.

**Comment by imageslr** [comment]
Also https://github.com/jgraph/drawio-desktop/issues/2#issuecomment-591564502
