### ISSUE TITLE
font issue when saving or loading file

### ISSUE THREAD

**Issue by ybrhue** [jgraph/drawio-desktop#413]
Snap 13.7.9 (latest) on latest manjaro with plasma.

See:

![image](https://user-images.githubusercontent.com/35401453/97424155-9bdc2880-1910-11eb-8dd5-e06582335e15.png)

**Comment by mararad** [comment]
Hi, 

we don't support manjaro (never tested it) so unfortunately, there is nothing we can suggest additionally.

Regards,

**Comment by tSlash99** [comment]
Same issue, Manjaro 20.1.2. Workaround : Drag & drop a diagram into the app.

**Comment by martinclauss** [comment]
Same problem under Fedora 32 and i3 window manager.

**Comment by comxd** [comment]
I have fixed this issue on a Kubuntu 20 using fc-cache:

```
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
fc-cache -r
```

**Comment by martinclauss** [comment]
I recently upgraded to Fedora 33. The problem still persists. Suggestions from @comxd unfortunately didn't work.

**Comment by SirStephanikus** [comment]
Same issue on XUbuntu 20.04 LTS and Ubuntu 20.04 LTS

**Comment by Cleeb122** [comment]
Hi, I'm experiencing the same issue on Manjaro. I understand Manjaro isn't supported, but I was wondering if there are any potential dependency fonts that might be missing. If so a fix may be to install the (potentially) missing fonts. Is there any information that may help?

**Comment by kenalexandersson** [comment]
I have the same problem on Fedora 35. Considering the creation date of this issue, am I to believe that that this issue is not prioritized, or no workaround will be presented?

**Comment by davidjgraph** [comment]
Duplicate of #368

**Comment by anescdev** [comment]
> I have fixed this issue on a Kubuntu 20 using fc-cache:
> 
> ```
> sudo rm /var/cache/fontconfig/*
> rm ~/.cache/fontconfig/*
> fc-cache -r
> ```

Working on Ubuntu 22.04

**Comment by Mehrab-Farhadzadeh** [comment]
> 

Worked on Ubuntu 20.04

**Comment by Mehrab-Farhadzadeh** [comment]
> I have fixed this issue on a Kubuntu 20 using fc-cache:
> 
> ```
> sudo rm /var/cache/fontconfig/*
> rm ~/.cache/fontconfig/*
> fc-cache -r
> ```

Worked on Ubuntu 20.04

**Comment by ltsali8220** [comment]
hey thanks it'w working on Kali Linux 24.04

**Comment by dabartmess** [comment]
> > I have fixed this issue on a Kubuntu 20 using fc-cache:
> > ```
> > sudo rm /var/cache/fontconfig/*
> > rm ~/.cache/fontconfig/*
> > fc-cache -r
> > ```
> 
> Working on Ubuntu 22.04

DOES NOT WORK...
