### ISSUE TITLE
Exporting PDF does not have background

### ISSUE THREAD

**Issue by bt-tech-dd** [jgraph/drawio-desktop#713]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When setting the background of a page to use another page in the same diagram, the exported PDF file does not show the background.

**To Reproduce**
1. Create a new diagram
2. Click on the plus sign to add a page (Page-2)
3. Drag a rectangle onto Page-2
4. Go back to Page-1
5. Click the Change button next to background
6. In the dropdown for the second radio button select Page-2
7. Click Apply
8. Go to File -> Export as -> PDF
9. Click the radio button for Pages
10. Uncheck the box for Include a copy of my diagram
11. Click Export
12. Click Save
13. Open the resulting PDF file

**Expected behavior**
The background page that was chosen should appear in the exported PDF file

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 15.2.7

**Desktop (please complete the following information):**
 - OS: Windows 10 version 2004 Build 19041.1237

**Comment by mararad** [comment]
Reproduced in 15.2.7 and Win 10.

**Comment by bt-tech-dd** [comment]
This bug is still present in 15.3.8.

**Comment by bt-tech-dd** [comment]
This bug is still present in version 15.8.7.

**Comment by ksiansf** [comment]
The bug is still present in 16.5.1

**Comment by bt-tech-dd** [comment]
This bug is still present in 17.2.4.

**Comment by kaage** [comment]
This bug is still present in 17.4.2

**Comment by johnvirg** [comment]
Unfortunately, this is still an issue in 20.2.3. The same thing happens whether exporting or printing. I am running desktop version on Windows 11.

If it helps, exporting to PNG works.

**Comment by davidrea** [comment]
This bug is still present in 20.3.0.

**Comment by francozzy** [comment]
This bug is still present in ver Web-based 20.5.3

**Comment by ghost** [comment]
The bug is still present in 20.3.0 on Mac OSX.  Web version 20.6.0 is running fine.

**Comment by davidjgraph** [comment]
Fixed in 20.7.4

**Comment by davidrea** [comment]
❤️ Thank you!!

**Comment by patefoniq** [comment]
Still present. I have ver. 22.1.18 and have white background.

**Comment by davidjgraph** [comment]
Please open as a new issue, the issue in this thread was fixed, it's likely any issue now is something else.
